package solver;
    dialect "java"

import org.optaplanner.core.api.score.buildin.hardsoft.HardSoftScoreHolder;

import domain.Packing;
import domain.Part;
import domain.Platform;

global HardSoftScoreHolder scoreHolder;

//*****************
// Hard Constraints
//*****************

rule "partOverlap"        //TODO: why does this produce a positive hard score?
    when
        $p1 : Part($id : id)
        $p2 : Part(intersects($p1) == true, id > $id)

    then
        if($p2.intersectArea($p1) < 1) {
            scoreHolder.addHardConstraintMatch(kcontext, -1);
        } else {
            scoreHolder.addHardConstraintMatch(kcontext, -$p2.intersectArea($p1));
        }
end

rule "outOfPlatformBoundsWidth"
    when
        $part : Part(widthOverlapsPlatform() == true, $id : id)
    then
        if($part.widthOverlap() < 1) {
            scoreHolder.addHardConstraintMatch(kcontext, -1);
        } else {
            scoreHolder.addHardConstraintMatch(kcontext, -$part.widthOverlap());
        }
end

rule "outOfPlatformBoundsHeight"
    when
        $part : Part(heightOverlapsPlatform() == true, $id : id)

    then
        if($part.heightOverlap() < 1) {
                scoreHolder.addHardConstraintMatch(kcontext, -1);
            } else {
                scoreHolder.addHardConstraintMatch(kcontext, -$part.heightOverlap());
            }
end

//*****************
// Soft Constraints
//*****************

rule "leftoverSpace"
    when
        $platform : Platform(isEmpty() == false, $id : id)
    then
                System.out.println("out of platform bounds width");
        scoreHolder.addSoftConstraintMatch(kcontext, -$platform.getLeftoverArea());
end