package solver;
    dialect "java"

import org.optaplanner.core.api.score.buildin.hardsoftdouble.HardSoftDoubleScoreHolder;

import domain.Packing;
import domain.Part;
import domain.Platform;

global HardSoftDoubleScoreHolder scoreHolder;

//*****************
// Hard Constraints
//*****************

rule "partOverlap"
    when
        $p1 : Part($id : id)
        $p2 : Part(id > $id)
        eval($p2.intersects($p1))

    then                             //TODO: why does this produce a positive hard score?
        scoreHolder.addHardConstraintMatch(kcontext, -$p2.intersectArea($p1));
end

rule "outOfPlatformBoundsWidth"
    when
        $part : Part($id : id)
        eval($part.widthOverlapsPlatform())
    then
        scoreHolder.addHardConstraintMatch(kcontext, -$part.widthOverlap());
        System.out.println("outOfPlatformBoundsWidth fired");
end

rule "outOfPlatformBoundsHeight"
    when
        $platform : Platform($height : height)
        $part : Part(platform == $platform, $partHeight : height + coordinates.getY())
        $compareHeight : Number($partHeight > $height)

    then
        scoreHolder.addHardConstraintMatch(kcontext, $height - $compareHeight.doubleValue());
        System.out.println("outOfPlatformBoundsHeight fired");
end

rule "partNotPlaced"
    when
        $part : Part(platform == null)
    then
        scoreHolder.addHardConstraintMatch(kcontext, -10.0);
        System.out.println("partNotPlaced fired");
end

//*****************
// Soft Constraints
//*****************

rule "leftoverSpace"
    when
        Platform($l : leftoverArea)
    then
        scoreHolder.addSoftConstraintMatch(kcontext, -$l);
        System.out.println("leftoverSpace fired");
end